# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9139bc8bac50a8be7f2b3609fe6e6c8155f4910ad6e9c725f49edfc7bd291e419148870f3656f9bd818661932599051842f187d48f9393b4626545a3924e9bfd

test:
  secret_key_base: 91e832e6566d8cbe6de8e35ad5f35d9e5c30a8af3b64acefd1889fa7750f9a15f4246ed6fdeb812b203bec851229602fe159d8b9279001ed0b1f6804f6763520

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
